config/routes.rb
Rails.application.routes.draw do
  
  get 'signup' => 'users/new'

  root 'welcome#home'

  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base

	has_attached_file :avatar, :styles =>
	{ :medium => "300x300>", :thumb => "100x100>" },
	:default_url => "/images/:style/missing.png"
	validates_attachment_content_type :avatar,
	:content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  	@user = User.all
  end

  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)
  	if @user.save 
      flash[:notice] = "Thank you for creating a new account."
  		redirect_to @user
  	else
  		flash[:alert] = "We're sorry. A new account could not be created. Please try again later."
  		redirect_to new_user_path
  	end
  end

  private
  
  def user_params
  		params.require(:user).permit(:fname, :lname, :username, :email, :password, :avatar)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paperclip</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Users Index</h1>

<% @user.each do |user| %>
	<%= user.fname %>
	<%= user.lname %>
	<br>
	<hr>
	<% end %>

<button id="new"><%= link_to 'Sign Up', new_user_path %></button>

app/views/users/new.html.erb
<h1>Sign-Up Here</h1>
  <%= form_for @user, :url => users_path, :html => { :multipart => true } do |f| %>
  <%=f.label :fname %>
  <%=f.text_field :fname %>
  <%=f.label :lname %>
  <%=f.text_field :lname %>
  <%=f.label :username %>
  <%=f.text_field :username %>
  <%=f.label :email %>
  <%=f.email_field :email %>
  <%=f.label :password %>
  <%=f.password_field :password %>
  <%= f.file_field :avatar %>
  <%=f.submit "Submit" %>
  
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.username %></h1>

<h2>This is your profile page, where you can view your profile picture.</h2>

<%= image_tag @user.avatar.url %>

app/views/welcome/home.html.erb
<h1>This is Paperclip</h1>

<p>For the best possible user experience, please sign up today!</p>

<button id="new"><%= link_to 'Sign Up', new_user_path %></button>

<p>Or if you're interested in viewing our current users, click below.</p>

<button id="new"><%= link_to 'Click here', users_path %></button>